config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @book = Book.new
  end
  
  def new 
    @book = Book.new
  end
  
  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to @book
    else
     @books = Book.all
     render action: :index
    end
  end
  
  def show
    @book = Book.find(params[:id])
  end
  
  def edit 
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully created."
      redirect_to @book
    else
     @books = Book.all
     render action: :edit
    end
  end
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path, notice: "Book was successfully destroyed."
  end
  
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_for(@book) do |f| %>
<%= render 'layouts/error_messages', model: f.object %>
  <%= f.label :title %>
  <div class="field">
    <%= f.text_field :title %>
  </div>
  <%= f.label :body %>
  <div class="field">
    <%= f.text_area :body %>
  </div>
  <%= f.submit 'Update Book' %>
<% end %>
<%= link_to "Show", book_path(@book) %>
<%= link_to "Back", books_path %>

  

app/views/books/index.html.erb
    <p id="notice"></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td><%= link_to "Show", book_path(book) %></td>
        <td><%= link_to "Edit", edit_book_path(book) %></td>
        <td><%= link_to "Destroy", book_path(book), method: :delete,
                                      data: { confirm: "You sure?" }  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h2>New book</h2>
<%= form_for(@book) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
  <div class="field">
    <div><%= f.label :Title %></div>
    <div><%= f.text_field :title %></div>
  </div>
  <div class="field">
    <div><%= f.label :Body %></div>
    <%= f.text_area :body %>
  </div>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @book.body %>
</p>
<%= link_to "Edit", edit_book_path(@book) %> |
<%= link_to "Back", books_path %>


  

app/views/home/index.html.erb
<h1>ようこそ <strong>Bookers</strong>  へ！</h1>
<p><strong>Bookers</strong>  では、さまざまな書籍に関するあなたの意見や</p><p>印象を共有し交換することができます</p>
<p><%= link_to "Start", books_path %></a></p>    	
  

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %> 
    <div class = "error_explanation">
        <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
        <ul>
            <% model.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Books</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash.notice.present? %>
      <p class="alert"><%= flash.notice %></div>
    <% end %>
    <%= yield %>
  </body>
</html>